name: Bot Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch: # ကိုယ်တိုင်နှိပ်ပြီး Run ချင်ရင် သုံးရန်

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyTelegramBotAPI requests

      - name: Run Telegram Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
